# Generated by Django 3.2.5 on 2021-07-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='post_rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='post_rating',
        ),
    ]
